version: '3.8'

services:
  nats:
    image: nats:latest
    command: 
      - "--js"  # Enable JetStream
      - "--server_name=nats-1"
      - "--cluster_name=gohustle"
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # HTTP monitoring
    volumes:
      - nats_data:/data
    environment:
      - NATS_SERVER_NAME=nats-1
      - NATS_CLUSTER_NAME=gohustle
    networks:
      - gohustle_network

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - gohustle_network

volumes:
  nats_data:
  redis_data:
    driver: local

networks:
  gohustle_network:
    driver: bridge 