version: '3.8'

services:
  redis:
    image: arm64v8/redis:6.0-alpine3.19
    ports:
      - "6379:6379"
    volumes:
      - 'redis_data:/data'
    command: ["redis-server", "--appendonly", "yes", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru"]
    deploy:
      resources:
        limits:
          memory: 384M
        reservations:
          memory: 128M

volumes:
  redis_data:
    driver: local