version: '3.8'

services:
  nats:
    image: nats:latest
    command: 
      - "--js"  # Enable JetStream
      - "--server_name=nats-1"
      - "--cluster_name=gohustle"
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # HTTP monitoring
    volumes:
      - nats_data:/data
    environment:
      - NATS_SERVER_NAME=nats-1
      - NATS_CLUSTER_NAME=gohustle
    networks:
      - gohustle_network

  redis:
    image: arm64v8/redis:6.0-alpine3.19
    ports:
      - "6379:6379"
    volumes:
      - 'redisData:/bitnami/redis/data'
    networks:
      - gohustle_network

volumes:
  nats_data:
  redisData:
    driver: local

networks:
  gohustle_network:
    driver: bridge 