apiVersion: v1
kind: Service
metadata:
  name: timescaledb
  namespace: gohustle
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: timescaledb
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: gohustle
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis 