version: '3.8'

services:
  redis:
    image: arm64v8/redis:6.0-alpine3.19
    ports:
      - "6379:6379"
    volumes:
      - 'redisData:/bitnami/redis/data'
  
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hustledb
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgbouncer:
    image: edoburu/pgbouncer:latest
    restart: always
    ports:
      - "6432:6432"
    environment:
      - DB_HOST=timescaledb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - LISTEN_PORT=6432
      - MAX_CLIENT_CONN=100
      - DEFAULT_POOL_SIZE=20
    depends_on:
      - timescaledb
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./users.txt:/etc/pgbouncer/users.txt

volumes:
  redisData:
    driver: local
  timescaledb_data:
    driver: local