apiVersion: v1
kind: ConfigMap
metadata:
  name: gohustle-config
data:
  config.yaml: |
    redis:
      host: "redis-service"
      port: 6379
      password: ""
      max_conns: 600
      min_idle_conns: 50
    kite:
      api_key: "your_api_key"
      api_secret: "your_api_secret"
      max_connections: 3