apiVersion: apps/v1
kind: Deployment
metadata:
  name: gohustle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gohustle
  template:
    metadata:
      labels:
        app: gohustle
    spec:
      containers:
      - name: gohustle
        image: gohustle:latest
        imagePullPolicy: Never
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: gohustle-config